version: '3.4'

services:
  iiasa.worldcereal.rdm.dbmigrator:
    image: ${DOCKER_REGISTRY-}iiasaworldcerealrdmdbmigrator
    build:
      context: .
      dockerfile: src/IIASA.WorldCereal.Rdm.DbMigrator/Dockerfile
    environment:
       ConnectionStrings:Default: "Host=ewocdb-dev1.cloud.geo-wiki.org;Port=4456;database=wcadmin;username=wcadmin;password=Tlxoi3TbRAbcDOLboq1l;"
